title: Why fruits are awesome
author: KingB
email: olowubusolaolutayo1992@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Fruits make you live a long healthy life. Fruits help you shed off body fat. Fruits help you have a clear skin. Fruits help you grow longer and stronger nails. Fruits help fight off sickness and diseases. Fruits helps in cleansing your body system

# social links
twitter_username: @kingB
github_username:  OlowuB

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
